### PR TITLE
2 cleanup commits

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @tvolkert – won't get travis green, but it'll get it closer

**Review by tvolkert — APPROVED** [review]

**Comment by kevmoo** [comment]
@tvolkert – do you understand the failures? What's the deal w/ the `Socket` class?

**Comment by tvolkert** [comment]
Yeah, it's because of https://github.com/dart-lang/http_io/pull/75

tldr: this package is a synthetic package (not published to Pub), and the changes in https://github.com/dart-lang/http_io/pull/75 needed to land with failures before https://dart-review.googlesource.com/c/sdk/+/104524 in order for the SDK change to land.

**Comment by tvolkert** [comment]
Specifically, see https://dart-review.googlesource.com/c/sdk/+/104524/9/DEPS

**Comment by kevmoo** [comment]
ack

**Pull request merged**
