### PR TITLE
Remove unused '_ServiceObject' stuff

### PR DESCRIPTION
**Pull request by zanderso**
Dead code.

Fixes https://github.com/dart-lang/http_io/issues/8

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
Nice!

**Comment by zanderso** [comment]
Why isn't travis running on this PR?

**Comment by kevmoo** [comment]
https://travis-ci.org/dart-lang/http_io/builds/324751802?utm_source=github_status&utm_medium=notification
?

**Comment by zanderso** [comment]
Yeah. The page helpfully refreshed right after I sent the message.

**Pull request merged**
