### PR TITLE
Try running on 1.24 stable

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by kevmoo** [comment]
Are we using the new `Function` syntax? That's likely causing the crash.

We could always go back to typedef...

**Comment by zanderso** [comment]
No. There's no use of the new `Function` syntax.

**Comment by zanderso** [comment]
Oh, when was the generic function syntax added? Maybe it wasn't stable yet in 1.24?
```
Tried calling: element
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      TypeResolverVisitor.visitGenericFunctionType (package:analyzer/src/generated/resolver.dart:9902)
#3      GenericFunctionTypeImpl.accept (package:analyzer/src/dart/ast/ast.dart:5774)
```

**Comment by kevmoo** [comment]
I swear it was in 1.24 – I think it was just broken in the analyzer.

We could always skip analyzer tests for 1.24 – although that would require
a lot more testing to increase our confidence...

**Comment by zanderso** [comment]
The plan is to move the http* tests from //tests/standalone_2/io.

**Comment by kevmoo** [comment]
Excellent!

In that case, we could just exclude analyzer from the stable run, right?

**Comment by zanderso** [comment]
Done

**Review by kevmoo — APPROVED** [review]
Guessing we're not hitting the code paths in tests that use the renamed consts...we'll get there eventually...

**Comment by zanderso** [comment]
Yeah, hitting some on my next PR. Will fix as I go.

**Pull request merged**
