### PR TITLE
Updates migrated from sdk repo

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Review by bkonyi — APPROVED** [review]

**Comment by bkonyi** [comment]
LGTM, but do we know why Travis is red? Looks like the IPv6 workaround isn't working anymore.

**Comment by zanderso** [comment]
Not sure. Maybe it's not needed anymore. I will try commenting out the commands.

**Comment by zanderso** [comment]
Looks like it's still needed.

**Comment by zanderso** [comment]
Needed to set sudo to true.

**Pull request merged**
